remote_theme: CaptainIRS/hacker-plus-theme

title: CaptainIRS
author: Rinish Sam
description: Personal site and Hackerblog of CaptainIRS
disqus_forum_shortname: captainirs-github-io
google_site_verification_content: mihn2QRzLfjm9AiHJFsco5EW-EiTIP17fueADOlFmj4
google_analytics: UA-173533812-1

# Usernames and badges
htb_badge_no: 303582 # Go to the HackTheBox site and copy your ID
thm_badge_no: 56356 # Go to https://tryhackme.com/profile -> Public Profile -> Get Badge ID
show_thm_htb_badges_in_nav: true
github_username: CaptainIRS
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: rinish-sam
twitch:
youtube:
twitter: CaptainIRS
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true